name: real_estate_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.6.1


dependencies:
  auto_route: ^9.3.0+1
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_hooks: ^0.20.5
  flutter_localizations:
    sdk: flutter
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.17
  intl: ^0.19.0



dev_dependencies:
  auto_route_generator: ^9.3.1
  flutter_gen_runner: ^5.9.0
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^7.0.0



flutter:
  uses-material-design: true

  assets:
    - assets/images/png/
    - assets/images/svg/

  fonts: 
    - family: Euclid-Circular-A
      fonts:
        - asset: assets/fonts/Euclid-Circular-A/Euclid-Circular-A-Bold.ttf
          weight: 700
        - asset: assets/fonts/Euclid-Circular-A/Euclid-Circular-A-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Euclid-Circular-A/Euclid-Circular-A-Medium.ttf
          weight: 500
        - asset: assets/fonts/Euclid-Circular-A/Euclid-Circular-A-Regular.ttf
          weight: 400


flutter_gen:
  output: lib/gen/
  line_length: 80

  assets:
    outputs:
      class_name: AppAssets

  integrations:
    flutter_svg: true